/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://sm7nrpps7fe3flfjqsgr5do47u.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zt4htpncdfa5plawzhra356etu",
    "aws_cognito_identity_pool_id": "ap-south-1:23727775-e653-4e3d-8646-36178dee3dbc",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_yqJ1mn946",
    "aws_user_pools_web_client_id": "7li76ler53evhsdom5a3dq6le9",
    "oauth": {}
};


export default awsmobile;
